### ISSUE TITLE
Message received twice when rocket chat server restarts

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/hubot-rocketchat#141]
When you restart/update your rocketchat server while hubot is running, messages will be received twice.
If you restart it again, they will be received 3 times and so on... 
This makes it lag really bad and to fix it you have to restart hubot each time you restart rocketchat.
It would be nice if this could be fixed so you don't have to do that every time

**Comment by geekgonecrazy** [comment]
@lucasvanhalst if you're running 0.37.0 of Rocket.Chat or higher... could you give the newest version of the adapter a try and see if this still happens to you?

**Comment by lucasvanhalst** [comment]
@geekgonecrazy Something must've gone wrong with building the latest version https://hub.docker.com/r/rocketchat/hubot-rocketchat/builds/
but I will give 1.0.2 a shot

**Comment by lucasvanhalst** [comment]
Can confirm this is still occurring with version 1.0.2
```
hubot         | [Wed Aug 24 2016 17:06:46 GMT+0000 (UTC)] INFO Preparing Meteor Subscriptions..
hubot         | [Wed Aug 24 2016 17:06:46 GMT+0000 (UTC)] INFO Subscribing to Room: __my_messages__
hubot         | [Wed Aug 24 2016 17:06:46 GMT+0000 (UTC)] INFO Successfully subscribed to messages
hubot         | [Wed Aug 24 2016 17:06:46 GMT+0000 (UTC)] INFO Setting up reactive message list...
hubot         | [Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)] INFO Message received with ID id
hubot         | [Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)] INFO Message receive callback id er4ALpnJLD2NrEHht ts Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)
hubot         | [Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)] INFO [Incoming] Lvh: bot ping
hubot         | [Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)] INFO Message sent to hubot brain.
hubot         | [Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)] INFO Message received with ID id
hubot         | [Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)] INFO Message receive callback id er4ALpnJLD2NrEHht ts Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)
hubot         | [Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)] INFO [Incoming] Lvh: bot ping
hubot         | [Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)] INFO Sending Message To Room: GENERAL
hubot         | [Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)] INFO Message received with ID id
hubot         | [Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)] INFO Message received with ID id
```

It does not send the message twice (if it is a command that triggers something), but it is received twice.

**Comment by geekgonecrazy** [comment]
Thanks for pointing out that v1.0.3 was missing.  I've pushed and corrected that.

I need to figure how to replicate this so we can determine what's going on.

**Comment by lucasvanhalst** [comment]
@geekgonecrazy 
hmm this got worse, now I had my bot receiving every message 9 times, but I didn't restart either rocketchat or the bot in about a week, so it must be something else.

**Comment by lucasvanhalst** [comment]
This is still happening. I've noticed you don't even have to restart the server for it to receive messages multiple times, at this moment my bot was receiving every message 3 times after being up for  about 4 days.

**Comment by geekgonecrazy** [comment]
@lucasvanhalst I have a bot instance that has been running for several months, even with upgrades and haven't ran into this.  Can you give me a bit more info on your full setup so we can try and narrow down a way to reproduce this?

**Comment by lucasvanhalst** [comment]
I can give you part of my docker-compose file:
```yaml
hubot:
  image: rocketchat/hubot-rocketchat:latest
  container_name: hubot
  environment:
    - ROCKETCHAT_URL=https://example.com
    - ROCKETCHAT_ROOM= GENERAL
    - ROCKETCHAT_USER=bot
    - ROCKETCHAT_PASSWORD=********
    - LISTEN_ON_ALL_PUBLIC=true
    - RESPOND_TO_DM=true
    - BOT_NAME=bot
    - RESPOND_TO_EDITED=true
    - MONGODB_URL=mongodb://mongo/hubot-brain
    - EXTERNAL_SCRIPTS=hubot-mongodb-brain,hubot-help,hubot-seen,hubot-diagnostics,hubot-strawpoll,hubot-youtube,hubot-tell,hubot-bro,hubot-reaction,hubot-loudbot,hubot-shipit,hubot-react-fork,hubot-fliptable,hubot-cleverbot,hubot-response,hubot-praise,hubot-thank-you,hubot-insulter,hubot-isup,hubot-geo,hubot-reminders,hubot-insanedomains,hubot-currency,hubot-image-linker
  links:
    - mongo:mongo
  ports:
    - 3001:8080
  volumes:
    - ./data/responses:/home/hubot/responses
```

Perhaps it has something to do with RESPOND_TO_EDITED now that I think of it.

**Comment by geekgonecrazy** [comment]
ah yes!  That probably plays into.  Can you try without it and see if that resolves?

**Comment by lucasvanhalst** [comment]
I'll give it a shot

**Comment by lucasvanhalst** [comment]
@geekgonecrazy That did not fix the issue. I only send this message once:
```
[Tue Dec 06 2016 19:43:18 GMT+0000 (UTC)] INFO Message received with ID id
[Tue Dec 06 2016 19:43:18 GMT+0000 (UTC)] INFO Message receive callback id XCnRZtSbPjTa9Tf8F ts Tue Dec 06 2016 19:43:18 GMT+0000 (UTC)
[Tue Dec 06 2016 19:43:18 GMT+0000 (UTC)] INFO [Incoming] Lvh: test
[Tue Dec 06 2016 19:43:18 GMT+0000 (UTC)] INFO Message sent to hubot brain.
[Tue Dec 06 2016 19:43:19 GMT+0000 (UTC)] INFO Message received with ID id
[Tue Dec 06 2016 19:43:19 GMT+0000 (UTC)] INFO Message receive callback id XCnRZtSbPjTa9Tf8F ts Tue Dec 06 2016 19:43:18 GMT+0000 (UTC)
[Tue Dec 06 2016 19:43:19 GMT+0000 (UTC)] INFO [Incoming] Lvh: test
[Tue Dec 06 2016 19:43:19 GMT+0000 (UTC)] INFO Sending Message To Room: GENERAL
[Tue Dec 06 2016 19:43:19 GMT+0000 (UTC)] INFO Message received with ID id
[Tue Dec 06 2016 19:43:19 GMT+0000 (UTC)] INFO Message received with ID id
```

**Comment by pandada8** [comment]
same here, sometimes the numbers of duplicated messages received just get insane (below pictures), and I can see the log show multiple `connected`, and sometimes, the messages just stoped to be received (I can confirm the overall network is good, maybe just some jitter or something else)
 
In the code asteroid reconnected and then go through the event binding again(`setupReactiveMessageList`), maybe actually attached multiple handler on the reactiveQuery ?

(just guess, have not tested yet)

![image](https://cloud.githubusercontent.com/assets/3305174/20981485/e4e2d91a-bcef-11e6-92a6-96c3aa2ceff7.png)

**Comment by geekgonecrazy** [comment]
@pandada8 interesting observation.  This could make sense.  Possibly there are multiple subscriptions to the same channel.  That would explain things.

**Comment by pandada8** [comment]
any plan in fixing this ?
I thought there should be some kind of rewrite the structure/flow of setting up handlers

**Comment by pandada8** [comment]
when subscriptions get more and more, I can see sometimes the bot cannot receive any new message. and in the log, I can only find bot connected again and again.

**Comment by lucasvanhalst** [comment]
So uh, any plan on fixing this? It's still happening, just rebooted my hubot instance after it received every message 10 times after being up for only a day

**Comment by geekgonecrazy** [comment]
@lucasvanhalst i'm still unable to replicate this.  If we can replicate it, we can most likely fix it pretty quickly

**Comment by lucasvanhalst** [comment]
Maybe it has to do with the server not having much resources. It only has 1GB of ram and one CPU, while running rocket.chat, mongodb, hubot and another webserver. I'm gonna give it a shot on another, more powerful server and see how it goes.

**Comment by akuma** [comment]
+1

**Comment by leonardorocc0** [comment]
I'm experiencing a similar issue, but I don't think it's related to rocketchat restart. 
Eg:
![image](https://user-images.githubusercontent.com/31746843/38773285-ae418c36-401e-11e8-90f0-2b9493819c06.png)

DEBUG Logs:
[Sat Apr 14 2018 22:58:27 GMT+0000 (UTC)] DEBUG Message '@punga_bot seen arleka' matched regex //./i/; listener.options = { id: null }
[Sat Apr 14 2018 22:58:27 GMT+0000 (UTC)] DEBUG Executing listener callback for Message '@punga_bot seen arleka'
[Sat Apr 14 2018 22:58:27 GMT+0000 (UTC)] DEBUG Message '@punga_bot seen arleka' matched regex //./i/; listener.options = { id: null }
[Sat Apr 14 2018 22:58:27 GMT+0000 (UTC)] DEBUG Executing listener callback for Message '@punga_bot seen arleka'
[Sat Apr 14 2018 22:58:27 GMT+0000 (UTC)] DEBUG Preparing message from string
[Sat Apr 14 2018 22:58:27 GMT+0000 (UTC)] INFO Message received with ID id
[Sat Apr 14 2018 22:58:27 GMT+0000 (UTC)] INFO Message received with ID id

**Comment by timkinnane** [comment]
@leonardorocc0 - which server version are you running. This could be a resource issue, that part I don't really understand, but I know there's been recent updates to core resolving issues with mongo performance - it also helps if you're using a `MONGO_OPLOG_URL`. Try that and please respond either way. This ticket is almost 2 years old and I'd like to close it if it's not the same issue.

**Comment by leonardorocc0** [comment]
rocketchat: 0.63.3
I don't think this is a resource issue, as it's running on a i5 8gb and % io/memory/cpu resources are fine!
@timkinnane let me show you an screenshot.
![image](https://user-images.githubusercontent.com/31746843/40290889-a43dbddc-5c97-11e8-9c50-b35aee6f9fe7.png)
[Mon May 21 2018 04:35:08 GMT+0000 (UTC)] INFO [Incoming] arleka: punga_bot devops me
[Mon May 21 2018 04:35:08 GMT+0000 (UTC)] INFO Message received with ID id
[Mon May 21 2018 04:35:08 GMT+0000 (UTC)] INFO Message receive callback id BLvXyLNpPQRvt2qis ts Mon May 21 2018 04:35:08 GMT+0000 (UTC)
[Mon May 21 2018 04:35:08 GMT+0000 (UTC)] INFO [Incoming] arleka: punga_bot devops me
[Mon May 21 2018 04:35:09 GMT+0000 (UTC)] INFO Message received with ID id
[Mon May 21 2018 04:35:09 GMT+0000 (UTC)] INFO Message receive callback id BLvXyLNpPQRvt2qis ts Mon May 21 2018 04:35:08 GMT+0000 (UTC)
[Mon May 21 2018 04:35:09 GMT+0000 (UTC)] INFO [Incoming] arleka: punga_bot devops me
[Mon May 21 2018 04:35:09 GMT+0000 (UTC)] INFO Looking up Room Name for: 6AwGM8cpmeJg2DoA7
[Mon May 21 2018 04:35:09 GMT+0000 (UTC)] INFO setting roomName: bots
[Mon May 21 2018 04:35:09 GMT+0000 (UTC)] INFO Message sent to hubot brain.
[Mon May 21 2018 04:35:09 GMT+0000 (UTC)] DEBUG Message 'punga_bot devops me' matched regex //.*//; listener.options = { id: null }
[Mon May 21 2018 04:35:09 GMT+0000 (UTC)] DEBUG Executing listener callback for Message 'punga_bot devops me'
[Mon May 21 2018 04:35:09 GMT+0000 (UTC)] DEBUG seen.add arleka on bots
[Mon May 21 2018 04:35:09 GMT+0000 (UTC)] DEBUG Message 'punga_bot devops me' matched regex //^\s*[@]?punga_bot[:,]?\s*(?:devops me)/i/; listener.options = { id: null }
[Mon May 21 2018 04:35:09 GMT+0000 (UTC)] DEBUG Executing listener callback for Message 'punga_bot devops me'
[Mon May 21 2018 04:35:09 GMT+0000 (UTC)] DEBUG Message 'punga_bot devops me' matched regex //./i/; listener.options = { id: null }
[Mon May 21 2018 04:35:09 GMT+0000 (UTC)] DEBUG Executing listener callback for Message 'punga_bot devops me'
[Mon May 21 2018 04:35:09 GMT+0000 (UTC)] DEBUG Message 'punga_bot devops me' matched regex //./i/; listener.options = { id: null }
[Mon May 21 2018 04:35:09 GMT+0000 (UTC)] DEBUG Executing listener callback for Message 'punga_bot devops me'

**Comment by timkinnane** [comment]
@leonardorocc0 have you enabled Mongo OPlog?
https://rocket.chat/docs/installation/manual-installation/multiple-instances-to-improve-performance/#check-your-database

**Comment by timkinnane** [comment]
Closing this issue because it's become a stale catch-all for different concerns. Please seek general support on [the #bots channel](https://open.rocket.chat/channel/bots) or start a new issue.
