### ISSUE TITLE
 Subscription not found

### ISSUE THREAD

**Issue by Micjoyce** [RocketChat/hubot-rocketchat#142]
When I run quick start hubot,I got this error, what wrong with me?

`
[Fri Jul 01 2016 01:12:03 GMT+0000 (UTC)] INFO Connecting To: 192.168.3.102:3000

[Fri Jul 01 2016 01:12:03 GMT+0000 (UTC)] INFO Successfully connected!

[Fri Jul 01 2016 01:12:03 GMT+0000 (UTC)] INFO GENERAL

[Fri Jul 01 2016 01:12:03 GMT+0000 (UTC)] INFO Logging In

[Fri Jul 01 2016 01:12:03 GMT+0000 (UTC)] INFO Successfully Logged In

[Fri Jul 01 2016 01:12:03 GMT+0000 (UTC)] INFO Looking up Room ID for: GENERAL

[Fri Jul 01 2016 01:12:03 GMT+0000 (UTC)] INFO Joining Room: GENERAL

[Fri Jul 01 2016 01:12:03 GMT+0000 (UTC)] INFO rid:  [ 'GENERAL' ]

[Fri Jul 01 2016 01:12:03 GMT+0000 (UTC)] INFO All rooms joined.

[Fri Jul 01 2016 01:12:03 GMT+0000 (UTC)] INFO Successfully joined room: GENERAL

[Fri Jul 01 2016 01:12:03 GMT+0000 (UTC)] INFO Preparing Meteor Subscriptions..

[Fri Jul 01 2016 01:12:03 GMT+0000 (UTC)] INFO Subscribing to Room:  __my_messages__

[Fri Jul 01 2016 01:12:03 GMT+0000 (UTC)] ERROR Unable to subscribe: {"error":404,"reason":"Subscription not 
found","message":"Subscription not found [404]","errorType":"Meteor.Error"} Reason: Subscription not found

[Fri Jul 01 2016 01:12:03 GMT+0000 (UTC)] ERROR {"error":404,"reason":"Subscription not 
found","message":"Subscription not found [404]","errorType":"Meteor.Error"}

[Fri Jul 01 2016 01:12:03 GMT+0000 (UTC)] ERROR Unable to complete setup. See https://github.com/RocketChat/
hubot-rocketchat for more info.
`

Why this subscribe "__my_messages__", some one can help me

**Comment by geekgonecrazy** [comment]
Looks like you grabbed a new version of the adapter.  Please grab version 0.1.4 of the adapter and try again :)

**Comment by timkinnane** [comment]
I'm having this issue on 0.1.4 as well. I think its more than just the Adapter version, but a mismatch with current RC version 0.35.0 (or develop branch), due to updates in the stream module.

I think version mismatches are leading to a bunch of issues being reported, because as far as I can tell:

- Adapter 0.1.4 safe with RC <= 0.34
- Adapter 1.0.0 had issues with all RC versions at time of release <= 0.35.0
- Adapter 1.0.1 seems the same, not sure
- Adapter #master post-release changes fix issues with RC >= 0.35.0

Need @geekgonecrazy to clarify. Maybe pin a note to the Readme?

**Comment by timkinnane** [comment]
Oops, there's actually already a note on readme, but maybe needs some more details about the specific version mismatches and to help anyone who might want to assist fixing the current mess.

Far as I can tell its due to incompatible updates to the [streamer package](https://github.com/RocketChat/meteor-streamer/tree/master/packages/rocketchat-streamer) within RC. The adapter uses [Asteroid](https://github.com/mondora/asteroid)'s [subscribe method](https://github.com/mondora/asteroid#subscribename-param1-param2-) to hook into room subscriptions set up by the RC streamer. The newer versions of the adapter (v1+) don't work with the old streamer (in RC releases) but if you're on RC develop branch, you **need** the v1+ adapter to work with the updated streamer.

@geekgonecrazy Is that remotely correct??

**Comment by timkinnane** [comment]
Confirming the details as discussed on RC demo with @Sing-Li. Here's the error log, running a fresh yo generated hubot with adapter 0.1.4 on RC #develop (post 0.35.0) branch.

```
[Wed Jul 20 2016 15:41:33 GMT+1000 (AEST)] DEBUG Loading adapter rocketchat
[Wed Jul 20 2016 15:41:33 GMT+1000 (AEST)] INFO Starting Rocketchat adapter version 0.1.4...
[Wed Jul 20 2016 15:41:33 GMT+1000 (AEST)] INFO Once connected to rooms I will respond to the name: test
[Wed Jul 20 2016 15:41:33 GMT+1000 (AEST)] INFO I will also respond to my Rocket.Chat username as an alias: testbot
[Wed Jul 20 2016 15:41:33 GMT+1000 (AEST)] INFO Connecting To: localhost:3000
[Wed Jul 20 2016 15:41:33 GMT+1000 (AEST)] INFO Successfully connected!
[Wed Jul 20 2016 15:41:33 GMT+1000 (AEST)] INFO newsfeed
[Wed Jul 20 2016 15:41:33 GMT+1000 (AEST)] INFO Logging In
[Wed Jul 20 2016 15:41:33 GMT+1000 (AEST)] INFO Successfully Logged In
[Wed Jul 20 2016 15:41:33 GMT+1000 (AEST)] INFO Looking up Room ID for: newsfeed
[Wed Jul 20 2016 15:41:33 GMT+1000 (AEST)] INFO Joining Room: GENERAL
[Wed Jul 20 2016 15:41:33 GMT+1000 (AEST)] INFO rid:  [ 'GENERAL' ]
[Wed Jul 20 2016 15:41:33 GMT+1000 (AEST)] INFO All rooms joined.
[Wed Jul 20 2016 15:41:33 GMT+1000 (AEST)] INFO Successfully joined room: GENERAL
[Wed Jul 20 2016 15:41:33 GMT+1000 (AEST)] INFO Preparing Meteor Subscriptions..
[Wed Jul 20 2016 15:41:33 GMT+1000 (AEST)] INFO Subscribing to Room: GENERAL
[Wed Jul 20 2016 15:41:33 GMT+1000 (AEST)] ERROR Unable to subscribe: {"error":404,"reason":"Subscription not found","message":"Subscription not found [404]","errorType":"Meteor.Error"} Reason: Subscription not found
[Wed Jul 20 2016 15:41:33 GMT+1000 (AEST)] ERROR {"error":404,"reason":"Subscription not found","message":"Subscription not found [404]","errorType":"Meteor.Error"}
[Wed Jul 20 2016 15:41:33 GMT+1000 (AEST)] ERROR Unable to complete setup. See https://github.com/RocketChat/hubot-rocketchat for more info.
```

By default yoeman uses `"hubot-rocketchat": "^1.0.1",` which actually works on the current #develop branch.

```
[Wed Jul 20 2016 15:44:45 GMT+1000 (AEST)] DEBUG Loading adapter rocketchat
[Wed Jul 20 2016 15:44:46 GMT+1000 (AEST)] INFO Starting Rocketchat adapter version 1.0.1...
[Wed Jul 20 2016 15:44:46 GMT+1000 (AEST)] INFO Once connected to rooms I will respond to the name: test
[Wed Jul 20 2016 15:44:46 GMT+1000 (AEST)] INFO I will also respond to my Rocket.Chat username as an alias: testbot
[Wed Jul 20 2016 15:44:46 GMT+1000 (AEST)] INFO Connecting To: localhost:3000
[Wed Jul 20 2016 15:44:46 GMT+1000 (AEST)] INFO Successfully connected!
[Wed Jul 20 2016 15:44:46 GMT+1000 (AEST)] INFO
[Wed Jul 20 2016 15:44:46 GMT+1000 (AEST)] INFO Logging In
[Wed Jul 20 2016 15:44:46 GMT+1000 (AEST)] INFO Successfully Logged In
[Wed Jul 20 2016 15:44:46 GMT+1000 (AEST)] INFO rid:  []
[Wed Jul 20 2016 15:44:46 GMT+1000 (AEST)] INFO All rooms joined.
[Wed Jul 20 2016 15:44:46 GMT+1000 (AEST)] INFO Preparing Meteor Subscriptions..
[Wed Jul 20 2016 15:44:46 GMT+1000 (AEST)] INFO Subscribing to Room: __my_messages__
[Wed Jul 20 2016 15:44:46 GMT+1000 (AEST)] INFO Successfully subscribed to messages
[Wed Jul 20 2016 15:44:46 GMT+1000 (AEST)] INFO Setting up reactive message list...
[Wed Jul 20 2016 15:44:46 GMT+1000 (AEST)] DEBUG Loading scripts from /Volumes/Code/git/timkinnane/test-bot/scripts
[Wed Jul 20 2016 15:44:46 GMT+1000 (AEST)] DEBUG Parsing help for /Volumes/Code/git/timkinnane/test-bot/scripts/example.coffee
[Wed Jul 20 2016 15:44:46 GMT+1000 (AEST)] DEBUG Loading scripts from /Volumes/Code/git/timkinnane/test-bot/src/scripts
[Wed Jul 20 2016 15:44:46 GMT+1000 (AEST)] DEBUG Loading hubot-scripts from /Volumes/Code/git/timkinnane/test-bot/node_modules/hubot-scripts/src/scripts
[Wed Jul 20 2016 15:44:46 GMT+1000 (AEST)] WARNING Loading scripts from hubot-scripts.json is deprecated and will be removed in 3.0 (https://github.com/github/hubot-scripts/issues/1113) in favor of packages for each script.
```

It successfully joins and responds to commands. However, the debug logs could be improved, e.g. `INFO rid:  []` looks like its got an empty array of rooms and `INFO Subscribing to Room: __my_messages__` seems misleading as there's no room called `_my_messages_`, I'm assuming that's the key for the Asteroid subscription.

Interestingly, when I set `export LISTEN_ON_ALL_PUBLIC=false` the bot reports more accurately: `INFO rid:  [ 'GENERAL' ]` and `INFO Successfully joined room: GENERAL`.

It seems like setting `LISTEN_ON_ALL_PUBLIC=true` overrides the `ROCKETCHAT_ROOM` list, maybe by design - however that isn't helpful if you've want the bot to join a private room.

**Comment by timkinnane** [comment]
Switching back to RC #master 0.35.0 with Hubot 0.1.4 **works**, so the problem is definitely with changes on #develop since 0.35.0.

FYI, If anyone want to repeat that test, here's the clean slate bot I used.
https://github.com/timkinnane/test-bot

**Comment by Sing-Li** [comment]
Ok. That explains why there is no mass uproar.  Since 0.35.0 is still 0.1.4 compatible.

We need to get the story straight before 0.36.0 though.   Thanks for your work @timkinnane !

**Comment by dbushong** [comment]
Aaaaand I guess I shouldn't have upgraded to 0.36.0 ;;

I tried -1.0.1, but now instead of the subscription error, any messages just result in this in the log:

```
[Wed Aug 03 2016 09:16:08 GMT-0700 (PDT)] INFO Message received with ID id
```

(and no response)

Anyone know if it's safe (db migration-wise) to switch back to using RC 0.35.0?

**Comment by dbushong** [comment]
Oh, correction - messages in channels work (addressed & otherwise), but DMs to the bot don't

**Comment by chispaa** [comment]
I upgraded to 0.36 and neither DMs or channels work.

```
hubot-3 [Wed Aug 03 2016 18:48:53 GMT-0400 (CLT)] ERROR Unable to subscribe: {"error":404,"reason":"Subscription not found","message":"Subscription not found [404]","errorType":"Meteor.Error"} Reason: Subscription not found
hubot-3 [Wed Aug 03 2016 18:48:53 GMT-0400 (CLT)] ERROR {"error":404,"reason":"Subscription not found","message":"Subscription not found [404]","errorType":"Meteor.Error"}
hubot-3 [Wed Aug 03 2016 18:48:53 GMT-0400 (CLT)] ERROR Unable to complete setup. See https://github.com/RocketChat/hubot-rocketchat for more info.
```
Any clues? Thanks!.

**Comment by dbushong** [comment]
@chispaa as i noted, hubot-rocketchat 1.0.1 works *better*, but DMs still don't work

**Comment by mrplow** [comment]
@dbushong how would one use 1.0.1?

I don't see any tags beyond 0.1.4

I'm using docker-compose and an a little annoyed with the breakage running the stable rocke chat image.

**Comment by timkinnane** [comment]
@mrplow you would have to [define the source in package.json](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) to specify [the branch that is ahead of 0.1.4](https://github.com/RocketChat/hubot-rocketchat/tree/streams), or even [the specific commit](https://github.com/RocketChat/hubot-rocketchat/commit/1e2281cbec196ddffa45f87f121247915a62ebb8) on that branch at 1.0.1 - I'm not sure if there's a risk using the head of that branch.

Or you could just stay on RC 0.35.0. That's probably easier and more stable.

I'm quite surprised 0.36.0 was actually released with the hubot incompatibility hang-over remaining.

**Comment by upbeta01** [comment]
I tried using the Rocket Chat docker version specified on the commit https://github.com/RocketChat/hubot-rocketchat/commit/195ac6a086e4bd7c6390abb5b6164c10a48aba54 but it's still giving me an error.

Live Guinea Pig (Test server):
```
Thu Aug 04 2016 15:15:40 GMT+0000 (UTC)] INFO Starting Rocketchat adapter version 0.1.4...
[Thu Aug 04 2016 15:15:40 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: bebot
[Thu Aug 04 2016 15:15:40 GMT+0000 (UTC)] INFO Connecting To: devopshq.org
[Thu Aug 04 2016 15:15:40 GMT+0000 (UTC)] INFO Successfully connected!
[Thu Aug 04 2016 15:15:40 GMT+0000 (UTC)] INFO devops_corner
[Thu Aug 04 2016 15:15:40 GMT+0000 (UTC)] INFO Logging In
[Thu Aug 04 2016 15:15:40 GMT+0000 (UTC)] INFO Successfully Logged In
[Thu Aug 04 2016 15:15:40 GMT+0000 (UTC)] INFO Looking up Room ID for: devops_corner
[Thu Aug 04 2016 15:15:40 GMT+0000 (UTC)] INFO Joining Room: GENERAL
[Thu Aug 04 2016 15:15:40 GMT+0000 (UTC)] INFO rid:  [ 'GENERAL' ]
[Thu Aug 04 2016 15:15:40 GMT+0000 (UTC)] INFO All rooms joined.
[Thu Aug 04 2016 15:15:40 GMT+0000 (UTC)] INFO Successfully joined room: GENERAL
[Thu Aug 04 2016 15:15:40 GMT+0000 (UTC)] INFO Preparing Meteor Subscriptions..
[Thu Aug 04 2016 15:15:40 GMT+0000 (UTC)] INFO Subscribing to Room: GENERAL
[Thu Aug 04 2016 15:15:40 GMT+0000 (UTC)] ERROR Unable to subscribe: {"error":404,"reason":"Subscription not found","message":"Subscription not found [404]","errorType":"Meteor.Error"} Reason: Subscription not found
[Thu Aug 04 2016 15:15:40 GMT+0000 (UTC)] ERROR {"error":404,"reason":"Subscription not found","message":"Subscription not found [404]","errorType":"Meteor.Error"}
[Thu Aug 04 2016 15:15:40 GMT+0000 (UTC)] ERROR Unable to complete setup. See https://github.com/RocketChat/hubot-rocketchat for more info.
```

The `bot` seems to be active as it shows a green status in the chatroom...

Just for the record, here is what `docker ps -a` shows.

```
$ docker ps -a
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS                    NAMES
61ce10336454        rocketchat/hubot-rocketchat:v0.1.4   "/bin/sh -c 'node -e "   15 minutes ago      Up 15 minutes       0.0.0.0:3001->8080/tcp   rocketchat_hubot_1
48cbb6ee1a9d        rocketchat/rocket.chat:latest        "node main.js"           16 minutes ago      Up 16 minutes       0.0.0.0:3000->3000/tcp   rocketchat_rocketchat_1
cc0813ad25f2        mongo:3.0                            "/entrypoint.sh mongo"   16 minutes ago      Up 16 minutes       27017/tcp                rocketchat_db_1
```

**Comment by timkinnane** [comment]
I've done some testing and it seems like adapter version `0.1.4` (which is current master) no longer works with Rocket.Chat master `0.36.0`.

Therefore you are required to downgrade either Rocket.Chat or the adapter for stability.

Some results testing adapter versions with RC master 0.36.0:

### 0.1.4 (master)

    ERROR {"error":404,"reason":"Subscription not found","message":"Subscription not found [404]","errorType":"Meteor.Error"}

Can connect to RC and appears as online, but doesn't respond because subscription broken.

### ^1.0.1 (generator default)

    [Fri Aug 05 2016 15:29:01 GMT+1000 (AEST)] INFO rid:  []
    [Fri Aug 05 2016 15:29:01 GMT+1000 (AEST)] INFO Subscribing to Room: __my_messages__

Works, but has log errors as above. Seems like its not getting room names properly.

### Streams branch (current development)

Setting dependency as `"hubot-rocketchat": "git://github.com/RocketChat/hubot-rocketchat#streams"`

As above, works fine, has log errors.


@Sing-Li @geekgonecrazy - can either of you comment on when/how this will be resolved.

Is the solution to release 1.0.1 as master, so at least both RC master and adapter master work together? Then fix the log errors in next patch?

I'd suggest a prominent warning in the readme, to run v0.1.4 if using RC version <0.35.0

**Comment by twhiting** [comment]
It broke it for us as well.

**Comment by Sing-Li** [comment]
0.36.0 was not anticipated to have breaking changes for hubot.

@rodrigok   has the "message" subscription been removed/disabled/renamed from 0.36.0 for some reason?    Thanks.

**Comment by timkinnane** [comment]
@Sing-Li I believe the issues [were identified](https://github.com/RocketChat/hubot-rocketchat/issues/142#issuecomment-233910282) on RC develop branch before the release.

Is there a process or guideline for releases to ensure stability with corresponding adapter versions? For instances reliant on Hubot compatibility like ours, this is making it quite complicated to stay current and even contributing is becoming challenging, re needing to keep rolling back for testing RC with adaptor and forward for submitting PRs.

**Comment by Sing-Li** [comment]
@timkinnane  are you saying:

1)  the issue no longer exists with the actual 0.36.0 release

OR

2) the issues were identified early -- so we should have smoothed out the transition by announcing the required changes beforehand  ?

Thanks for clarifying 😄

**Comment by twhiting** [comment]
The issue definitely exists on 0.36.0 our bot is currently useless.

**Comment by rodrigok** [comment]
@Sing-Li Our master and development branch should be working with hubot, we didn't merge the cache branch yet.

**Comment by rodrigok** [comment]
@Sing-Li @twhiting I just tried the hubot with our develop branch, it's working

**Comment by twhiting** [comment]
Hmm any idea why i'd be getting this error then? The only thing that changed from a working bot to now is upgrading rocketchat to 0.36.0.

```
[Tue Aug 09 2016 16:29:13 GMT-0600 (Mountain Daylight Time)] INFO Preparing Meteor Subscriptions..
[Tue Aug 09 2016 16:29:13 GMT-0600 (Mountain Daylight Time)] INFO Subscribing to Room: gFASS3j4A8u85WiHX
[Tue Aug 09 2016 16:29:13 GMT-0600 (Mountain Daylight Time)] ERROR Unable to subscribe: {"error":404,"reason":"Subscription not found","message":"Subscription not found [404]","errorType":"Meteor.Error"} Reason: Subscription not found
[Tue Aug 09 2016 16:29:13 GMT-0600 (Mountain Daylight Time)] ERROR {"error":404,"reason":"Subscription not found","message":"Subscription not found [404]","errorType":"Meteor.Error"}
[Tue Aug 09 2016 16:29:13 GMT-0600 (Mountain Daylight Time)] ERROR Unable to complete setup. See https://github.com/RocketChat/hubot-rocketchat for more info.
```

The bot won't respond to any commands but still shows as "online"

**Comment by rodrigok** [comment]
@twhiting awesome, please let us know if this fixed your issue.

**Comment by twhiting** [comment]
@rodrigok see my update, still having issues. Not sure why.

**Comment by rodrigok** [comment]
@twhiting the version you should use is the latest version `1.0.1`, not `0.1.4`

**Comment by timkinnane** [comment]
@Sing-Li, I was responding to your comment...

> 0.36.0 was not anticipated to have breaking changes for hubot.

That seemed incorrect because the issues were previously identified before 0.36.0. You said yourself, 20 days prior:

> We need to get the story straight before 0.36.0

But there was no resolution before 0.36.0 release, it just cemented the current issues.
Perhaps its just a miscommunication of issues with RC vs issues with adapter.

@rodrigok please see [my comment](https://github.com/RocketChat/hubot-rocketchat/issues/142#issuecomment-237759722) detailing issues with 1.0.1. It works better than the 0.1.4 with RC 0.36.0, but there's still some log errors and the 1.0.1 release should probably be made on the master branch of this repo if that's the current best version, no?

**Comment by rodrigok** [comment]
@timkinnane which errors do you have with version 1.0.1?

**Comment by Sing-Li** [comment]
@rodrigok basically everyone was using 0.1.4 with 0.35.0  

So with 0.36.0 we need to use 1.0.1 ?   Has improvement/more-stream been merged down with 0.36.0 then? 

@timkinnane   we're trying to work out what got merged into core (the hubot adapter MUST match) ... and what gets merged down (unfortunately) is frequently a last minute decision

**Comment by rodrigok** [comment]
@Sing-Li As I said before, we didn't merge the `improvement/more-stream` into develop, we will do it tomorrow (maybe)

The version 1.0.0 was compatible with `improvement/more-stream`, and you guys reverted the code to be compatible with `develop` again with the version 1.0.1. Do you remember?

**Comment by Silvenga** [comment]
@rodrigok @Sing-Li I'm not using Hubot, but I did base the original functionality of a dotNet port called Rocket.Chat.Net (https://github.com/Silvenga/Rocket.Chat.Net) on it. When I upgraded to RC 0.36.0 my library was found to be incompatible in the same way as Hubot. 

What I've experienced:
- Subscriptions to `stream-messages` result in 404's (similar to 0.1.4 behavior). 
- Subscribing to room information was broken 
- I upgraded to be inline with 1.0.1 from the Hubot `stream` branch by
 - Message `type` from `added` to `changed`
 - Subscription name changed from `stream-messages` to `stream-room-messages`
 - Use 2nd index of `args` from the 1st index on the Rocket.Chat messages JSON objects. 
 - Subscribing to all rooms from `null` to `__my_messages__`
 - Sending `true` instead of the never used "Message Subscription Limit"

It appears, with these changes, that my library can now receive messages from itself via `__my_messages__` and `stream-room-messages`, however, messages sent from other users are not propagated. This behavor is described here: https://github.com/RocketChat/hubot-rocketchat/issues/149 

> Is there a process or guideline for releases to ensure stability with corresponding adapter versions? For instances reliant on Hubot compatibility like ours, this is making it quite complicated to stay current and even contributing is becoming challenging, re needing to keep rolling back for testing RC with adaptor and forward for submitting PRs.

I'm worried about my continued support of my Rocket.Chat driver if the API breaks on a release without an upgrade path. Although, with that said, having to reverse engineer the protocol and dive into the client/server code is extremely frustrating. MeteorJs makes cross-language integration so very difficult.

**Comment by rodrigok** [comment]
@Silvenga Sorry about that, we are in beta so some times we expect changes like that. Now we are in the middle of 2 big changes, the stream package and a new cache layer on the server side. This is very necessary right now to allow deployments with a large amount of users.

We need to create a separated list of methods to be used as API, then we can keep the compatibility while we are changing the main methods to improve things.

We will try to prevent changes like this in the future.

**Comment by Sing-Li** [comment]
@rodrigok I am trying to understand this:

a)  0.1.4 worked with 0.35.0 
b) there is no core changes between 0.35.0 and 0.36.0  [as you repeatedly said, the merge down is yet to come]
c)  BUT 0.1.4 no longer works with 0.36.0

What has changed in core that makes 0.1.4 no longer work with 0.36.0

**Comment by twhiting** [comment]
@rodrigok Version 1.0.1 was the version I had before the upgrade i performed yesterday, was still broken for me.

**Comment by geekgonecrazy** [comment]
> (as a sidenote, I do not think 1.0.1 is a rollback at all, it is 1.0.0 - @geekgonecrazy please confirm)

I can confirm.  v1.0.1 is not a rollback.  

My best advice right now is stick with 0.35.0 of Rocket.Chat and 0.1.4 of the hubot adapter.  Once we get these new changes released on Rocket.Chat server.  Hopefully we can make them in 0.37.0.  Then we can finally be back on the same page.

I apologize guys... We're trying to get things synced back up for everyone.  Turning out to be more difficult then it should be :smile:

**Comment by timkinnane** [comment]
Cheers @geekgonecrazy. That's a good solution, I think we'll going to skip 0.36.0 and wait for stability. Maybe this needs a notice to both repo readmes? The #hubot channel description in demo.rocket.chat links to [the old message](https://github.com/RocketChat/hubot-rocketchat/blob/master/README.md#important), but its not there anymore.

**Comment by richardwlu** [comment]
@geekgonecrazy Has this issue been addressed in 0.37.0? We updated RC from .31 to .36 and our bot doesn't work as described above. 

Though we are on super old 0.0.22 hubot-rocketchat adapter. Just having unrelated `npm ERR! not a package /tmp/npm-17133-bGAuMrU7/github.com/RocketChat/asteroid.git
npm ERR! Error: ENOENT, open '/tmp/npm-17133-bGAuMrU7/github.com/RocketChat/asteroid.git-unpack/package.json'` issues trying to run yo now to get a fresh hubot and not sure why.

**Comment by inty** [comment]
I'm running 0.37.0 (worked fine with 0.35.0) and can't get it working with 0.1.4, 1.0.1 or 1.0.4. I'm getting this though...

```
ERROR Unable to Login: {"error":400,"reason":"Unrecognized options for login request","message":"Unrecognized options for login request [400]","errorType":"Meteor.Error"} Reason: Unrecognized options for login request
```

**Comment by richardwlu** [comment]
@inty Are you trying to log hubot in through ldap or the traditional method?

**Comment by inty** [comment]
@richardwlu I'm using LDAP.

**Comment by TheReal1604** [comment]
Same here.. 0.37.1 in use and hubot v0.1.4 adapter is broken with HTTP 404.

**Comment by CONFORM-IT** [comment]
Same as @inty - after updating from 0.36 with adapter 1.0.1 to 0.37.1, we got the error 400. Restored from backup for now.

**Comment by geekgonecrazy** [comment]
Yeah I can confirm.  Adapter version 0.1.4 does not work with 0.36.0 or 0.37.x currently.  Investigating..

**Comment by antgel** [comment]
Hi all, is anyone from the RC team investigating this? I see it's officially "unassigned".

**Comment by lhaig** [comment]
I have the same issue with subscriptions. New Docker based install

    hubot_1       | [Tue Aug 23 2016 13:36:10 GMT+0000 (UTC)] ERROR Unable to subscribe: {"error":404,"reason":"Subscription not found","message":"Subscription not found [404]","errorType":"Meteor.Error"} Reason: Subscription not found
    hubot_1       | [Tue Aug 23 2016 13:36:10 GMT+0000 (UTC)] ERROR {"error":404,"reason":"Subscription not found","message":"Subscription not found [404]","errorType":"Meteor.Error"}
    hubot_1       | [Tue Aug 23 2016 13:36:10 GMT+0000 (UTC)] ERROR Unable to complete setup. See https://github.com/RocketChat/hubot-rocketchat for more info.

**Comment by geekgonecrazy** [comment]
@antgel officially.  No one is assigned. I'm taking a look though.  :wink:

Can you guys give version 1.0.1 of the adapter a try if you're using 0.37.0 of rocket.chat?  I tried it and it worked

**Comment by inty** [comment]
Tried 1.0.1 again, now I'm running 0.37.1 though and I get the same result (400 error).

**Comment by geekgonecrazy** [comment]
@inty your particular issue seems to be related to the login.  Can you give me the command you're using to run it?  I think we can help you get it sorted by specifying the right login options.  :smile:

**Comment by antgel** [comment]
@geekgonecrazy Great to hear! This is blocking our adoption, no bot == no dice. ;)

I believe I tried 1.0.1 and it was the same - others reported above that this combo didn't work, no? I can try again tomorrow if you're 100% sure it works (and if it does, why all the noise here ? :) ).

**Comment by geekgonecrazy** [comment]
@antgel I hear that.  Pretty important for chatops.

Note this is with Rocket.Chat version 0.37.0 or 0.37.1 and hubot adapter version 1.0.1.  

npm will have the release because we couldn't roll it back.  But Docker will not have 1.0.1 since we were able to yank those images.

If I can get one more person to confirm they have it working, i'm going to go ahead and cut 1.0.2 and npm / docker will both exist.

**Comment by inty** [comment]
@geekgonecrazy Here's an excerpt from the script I'm using with sensitive stuff omitted.

```
#!/bin/bash

export ROCKETCHAT_ROOM='<omitted>'
export ROCKETCHAT_URL=https://rocket.<omitted>/
export ROCKETCHAT_USER=<omitted>
export ROCKETCHAT_PASSWORD=<omitted>
export ROCKETCHAT_AUTH=ldap

./bin/hubot -a rocketchat
```

Doesn't leave that much room for error? :) And It worked with 0.35 like a said above.

**Comment by geekgonecrazy** [comment]
@inty ah ldap! ok its possible something changed Rocket.Chat side between 0.35 and now with ldap.  Looking into it.

**Comment by geekgonecrazy** [comment]
@inty found it.  Yes an additional check was added server side for the login.

**Comment by dbushong** [comment]
I upgraded to 1.0.1 to get 0.36 working again, which it did except for direct messaging, which no longer worked.  As of 0.37.1, it still mostly works, but now for some reason the "help" command no longer works (!?) (and direct messaging is still broken)

**Comment by geekgonecrazy** [comment]
@inty release cut, and ldap fix is present in [v1.0.3](https://github.com/RocketChat/hubot-rocketchat/releases/tag/v1.0.3)

@dbushong are you setting RESPOND_TO_DM=true?

**Comment by geekgonecrazy** [comment]
@dbushong if you don't mind could you open a new issue for this, if that doesn't resolve?

I'm going to go ahead and close this issue, as the root issue should now be resolved.

**Comment by dbushong** [comment]
Ah hah, `RESPOND_TO_DM=true` fixed the DM problem, thanks!  (I didn't read the 1.0.1 docs)

`help` (both via DM & in channel when addressed) is still broken as of 0.37.1 tho (I upgraded RocketChat and not Hubot this time, and that's when it broke)

**Comment by geekgonecrazy** [comment]
@dbushong good deal!  Lets open another issue and try and track down why help isn't working.  Its working on mine.

**Comment by inty** [comment]
@geekgonecrazy Thanks, it works now!

**Comment by antgel** [comment]
I just pulled latest in docker, and it's working here too. Thanks all! :D

**Comment by dytec** [comment]
Working and also `help` command 👍

**Comment by geekgonecrazy** [comment]
Thanks for testing and reporting back guys!  Sorry about the complications.  I hope to prevent these in the future 👍

**Comment by lhaig** [comment]
Hi All,

Just confirming that the updates work in the containers

Lance

**Comment by twhiting** [comment]
👍 Working here as well

**Comment by geekgonecrazy** [comment]
Awesome guys!  👍

**Comment by wargamesqcf** [comment]
Will confirm that v1.0.3 of the hubot interface worked for 37.1

**Comment by Hostile** [comment]
just installed latest Rocket chat .038.0 and its not working with hubot  0.1.4

`[Mon Sep 05 2016 06:18:23 GMT+0000 (UTC)] INFO Starting Rocketchat adapter version 0.1.4...
[Mon Sep 05 2016 06:18:23 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: hihouhou
[Mon Sep 05 2016 06:18:23 GMT+0000 (UTC)] INFO I will also respond to my Rocket.Chat username as an alias: bot
[Mon Sep 05 2016 06:18:23 GMT+0000 (UTC)] WARNING No services ROCKETCHAT_ROOM provided to Hubot, using GENERAL
[Mon Sep 05 2016 06:18:23 GMT+0000 (UTC)] INFO Connecting To: chat.vodeoo.com:3000
[Mon Sep 05 2016 06:18:23 GMT+0000 (UTC)] INFO Successfully connected!
[Mon Sep 05 2016 06:18:23 GMT+0000 (UTC)] INFO GENERAL
[Mon Sep 05 2016 06:18:23 GMT+0000 (UTC)] INFO Logging In
[Mon Sep 05 2016 06:18:23 GMT+0000 (UTC)] INFO Successfully Logged In
[Mon Sep 05 2016 06:18:23 GMT+0000 (UTC)] INFO Looking up Room ID for: GENERAL
[Mon Sep 05 2016 06:18:23 GMT+0000 (UTC)] INFO Joining Room: GENERAL
[Mon Sep 05 2016 06:18:23 GMT+0000 (UTC)] INFO rid:  [ 'GENERAL' ]
[Mon Sep 05 2016 06:18:23 GMT+0000 (UTC)] INFO All rooms joined.
[Mon Sep 05 2016 06:18:23 GMT+0000 (UTC)] INFO Successfully joined room: GENERAL
[Mon Sep 05 2016 06:18:23 GMT+0000 (UTC)] INFO Preparing Meteor Subscriptions..
[Mon Sep 05 2016 06:18:23 GMT+0000 (UTC)] INFO Subscribing to Room: GENERAL
[Mon Sep 05 2016 06:18:24 GMT+0000 (UTC)] ERROR Unable to subscribe: {"error":404,"reason":"Subscription not found","message":"Subscription not found [404]","errorType":"Meteor.Error"} Reason: Subscription not found
[Mon Sep 05 2016 06:18:24 GMT+0000 (UTC)] ERROR {"error":404,"reason":"Subscription not found","message":"Subscription not found [404]","errorType":"Meteor.Error"}
[Mon Sep 05 2016 06:18:24 GMT+0000 (UTC)] ERROR Unable to complete setup. See https://github.com/RocketChat/hubot-rocketchat for more info.
`

**Comment by geekgonecrazy** [comment]
@Hostile as mentioned earlier in this ticket and now in the README.  0.38.0 of Rocket.Chat requires v1.0.3 of the hubot adapter.

**Comment by seanxlliu** [comment]
@geekgonecrazy the issue still remains. Let me how I can debug to provide more information.

i created and was running v0.39.0, neither hubot v1.0.3 nor v1.0.4 docker image works.

hubot_1       | [Mon Sep 19 2016 06:29:22 GMT+0000 (UTC)] INFO Successfully connected!
hubot_1       | [Mon Sep 19 2016 06:29:22 GMT+0000 (UTC)] INFO GENERAL
hubot_1       | [Mon Sep 19 2016 06:29:22 GMT+0000 (UTC)] INFO Logging In
hubot_1       | [Mon Sep 19 2016 06:29:22 GMT+0000 (UTC)] INFO Successfully Logged In
hubot_1       | [Mon Sep 19 2016 06:29:22 GMT+0000 (UTC)] INFO Looking up Room ID for: GENERAL
hubot_1       | [Mon Sep 19 2016 06:29:22 GMT+0000 (UTC)] INFO Joining Room: GENERAL
hubot_1       | [Mon Sep 19 2016 06:29:22 GMT+0000 (UTC)] INFO rid:  [ 'GENERAL' ]
hubot_1       | [Mon Sep 19 2016 06:29:22 GMT+0000 (UTC)] INFO All rooms joined.
hubot_1       | [Mon Sep 19 2016 06:29:22 GMT+0000 (UTC)] INFO Successfully joined room: GENERAL
hubot_1       | [Mon Sep 19 2016 06:29:22 GMT+0000 (UTC)] INFO Preparing Meteor Subscriptions..
hubot_1       | [Mon Sep 19 2016 06:29:22 GMT+0000 (UTC)] INFO Subscribing to Room: GENERAL
hubot_1       | [Mon Sep 19 2016 06:29:22 GMT+0000 (UTC)] ERROR Unable to subscribe: {"error":404,"reason":"Subscription not found","message":"Subscription not found [404]","errorType":"Meteor.Error"} Reason: Subscription not found
hubot_1       | [Mon Sep 19 2016 06:29:22 GMT+0000 (UTC)] ERROR {"error":404,"reason":"Subscription not found","message":"Subscription not found [404]","errorType":"Meteor.Error"}
hubot_1       | [Mon Sep 19 2016 06:29:22 GMT+0000 (UTC)] ERROR Unable to complete setup. See https://github.com/RocketChat/hubot-rocketchat for more info.

**Comment by daemienb** [comment]
@geekgonecrazy I'm seeing the issue in 0.45 non docker install - 

I've used npm install hubot-rocketchat@1 : should i be using a different hubot version?  and how do i upgrade or downgrade?
Thanks

[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Starting Rocketchat adapter version 0.1.4...
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Once connected to rooms I will respond to the name: alfred
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] WARNING No services ROCKETCHAT_URL provided to Hubot, using localhost:3000
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] WARNING No services ROCKETCHAT_ROOM provided to Hubot, using GENERAL
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Connecting To: localhost:3000
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Successfully connected!
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO GENERAL
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Logging In
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Successfully Logged In
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Looking up Room ID for: GENERAL
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Joining Room: GENERAL
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO rid:  [ 'GENERAL' ]
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO All rooms joined.
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Successfully joined room: GENERAL
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Preparing Meteor Subscriptions..
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Subscribing to Room: GENERAL
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] ERROR Unable to subscribe: {"error":404,"reason":"Subscription 'stream-messages' not found","message":"Subscription 'stream-messages' not found [404]","errorType":"Meteor.Error"} Reason: Subscription 'stream-messages' not found
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] ERROR {"error":404,"reason":"Subscription 'stream-messages' not found","message":"Subscription 'stream-messages' not found [404]","errorType":"Meteor.Error"}
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] ERROR Unable to complete setup. See https://github.com/RocketChat/hubot-rocketchat for more info.

**Comment by geekgonecrazy** [comment]
@daemienb 
> [Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Starting Rocketchat adapter version 0.1.4...

You're on adapter version 0.1.4 for some reason.  :)
